# Generated by Django 3.1.7 on 2021-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(default='cofetar-patiser', max_length=60),
        ),
    ]
