# Generated by Django 3.1.7 on 2021-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0002_team_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='insta',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
    ]
