# Generated by Django 3.1.7 on 2021-02-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0004_auto_20210226_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
