# Generated by Django 3.1.7 on 2021-02-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0005_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_photo', models.ImageField(upload_to='interior')),
                ('recipe_photo', models.ImageField(upload_to='recipes')),
            ],
        ),
    ]
