# Generated by Django 3.1.7 on 2021-02-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0006_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
