# Generated by Django 3.1.7 on 2021-02-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0008_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('Recipes', 'Recipes'), ('Interior', 'Interior')], default='recipe', max_length=200),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=200)),
                ('price_tag', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='menu')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_title', to='artisan_app.recipecategory')),
            ],
        ),
    ]
