# Generated by Django 3.1.7 on 2021-02-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0009_auto_20210226_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price_tag',
            field=models.IntegerField(),
        ),
    ]
