# Generated by Django 3.1.7 on 2021-02-26 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0011_auto_20210226_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
