# Generated by Django 3.1.7 on 2021-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0013_auto_20210226_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
