# Generated by Django 3.1.7 on 2021-02-28 19:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0015_auto_20210226_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
