# Generated by Django 3.1.7 on 2021-02-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0016_slogan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slogan',
            old_name='name',
            new_name='brand',
        ),
    ]
