# Generated by Django 3.1.7 on 2021-02-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0017_auto_20210228_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slogan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
