# Generated by Django 3.1.7 on 2021-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0018_auto_20210228_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Gallery', max_length=200),
        ),
    ]
