# Generated by Django 3.1.7 on 2021-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0020_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
