# Generated by Django 3.1.7 on 2021-03-10 21:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0023_blogcategories_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('traditions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('history', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
