# Generated by Django 3.1.7 on 2021-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0025_auto_20210310_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='history_image',
            field=models.ImageField(default='static/img/about_3.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='story',
            name='service_image',
            field=models.ImageField(default='static/img/about_2.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='story',
            name='traditions_image',
            field=models.ImageField(default='static/img/about_1.jpg', upload_to=''),
        ),
    ]
