# Generated by Django 3.1.7 on 2021-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0026_auto_20210311_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='Workshop', max_length=200),
        ),
    ]
