# Generated by Django 3.1.7 on 2021-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0027_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='static/img/events_poetry.jpg', upload_to=''),
        ),
    ]
