# Generated by Django 3.1.7 on 2021-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0028_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default='author', max_length=300),
            preserve_default=False,
        ),
    ]
