# Generated by Django 3.1.7 on 2021-03-11 16:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('artisan_app', '0029_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
