# Generated by Django 3.1.7 on 2021-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0030_comments_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='slogan',
            name='motto',
            field=models.CharField(default='Cake & Coffee Shop', max_length=200),
            preserve_default=False,
        ),
    ]
