# Generated by Django 3.1.7 on 2021-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0031_slogan_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(default='.menu_breakfast', max_length=150),
        ),
    ]
