# Generated by Django 3.1.7 on 2021-03-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0032_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price_tag',
            field=models.CharField(max_length=10),
        ),
    ]
