# Generated by Django 3.1.7 on 2021-03-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0033_auto_20210312_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='measurement',
            field=models.CharField(choices=[('LEI/KG', 'LEI/KG'), ('LEI/BUC', 'LEI/BUC')], default='LEI/KG', max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price_tag',
            field=models.IntegerField(),
        ),
    ]
