# Generated by Django 3.1.7 on 2021-03-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0035_facts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facts',
            new_name='Fact',
        ),
    ]
