# Generated by Django 3.1.7 on 2021-03-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('artisan_app', '0036_auto_20210313_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategories',
            new_name='BlogCategory',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
