# Generated by Django 3.1.7 on 2021-03-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0037_auto_20210313_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='category',
            new_name='category_en',
        ),
        migrations.AddField(
            model_name='fact',
            name='category_ro',
            field=models.CharField(default='add something', max_length=20),
            preserve_default=False,
        ),
    ]
