# Generated by Django 3.1.7 on 2021-03-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0041_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
