# Generated by Django 3.1.7 on 2021-03-20 22:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0043_auto_20210321_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='about_us_page',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
