# Generated by Django 3.1.7 on 2021-03-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0044_story_about_us_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='motto',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='signature',
            field=models.ImageField(default='static/img/about_3.jpg', upload_to=''),
        ),
    ]
