# Generated by Django 3.1.7 on 2021-03-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0045_auto_20210321_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='about_us_image',
            field=models.ImageField(default='static/img/info_img2.jpg', upload_to=''),
        ),
    ]
