# Generated by Django 3.1.7 on 2021-03-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0047_newsletterusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterusers',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
