# Generated by Django 3.1.7 on 2021-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0048_auto_20210323_0748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterUsers',
            new_name='NewsletterUser',
        ),
    ]
