# Generated by Django 3.1.7 on 2021-03-27 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0052_sendemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
