# Generated by Django 3.1.7 on 2021-03-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0055_auto_20210328_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='NewsletterUser',
        ),
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
