# Generated by Django 3.1.7 on 2021-03-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0057_newsletteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletteruser',
            old_name='comfirmed',
            new_name='confirmed',
        ),
    ]
