# Generated by Django 3.1.7 on 2021-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0059_sendemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
