# Generated by Django 3.1.7 on 2021-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0060_auto_20210329_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
