# Generated by Django 3.1.7 on 2021-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0061_auto_20210329_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='figures',
            field=models.CharField(max_length=20),
        ),
    ]
