# Generated by Django 3.1.7 on 2021-03-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0062_auto_20210401_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
