# Generated by Django 3.1.7 on 2021-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0063_delete_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_en', models.CharField(max_length=20)),
                ('category_ro', models.CharField(max_length=20)),
                ('figures', models.CharField(max_length=20)),
            ],
        ),
    ]
