# Generated by Django 3.1.7 on 2021-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0067_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
