# Generated by Django 3.1.7 on 2021-04-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0069_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='views_count',
        ),
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddres', models.GenericIPAddressField(default='84.232.140.116')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_app.blogpost')),
            ],
        ),
    ]
