# Generated by Django 3.1.7 on 2021-04-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0070_auto_20210403_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
