# Generated by Django 3.1.7 on 2021-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0073_auto_20210405_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='workshop', max_length=200),
        ),
    ]
