# Generated by Django 3.1.7 on 2021-04-15 18:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0075_menu_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_subject', models.CharField(default='', max_length=200)),
                ('contact_message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contact_author', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
