# Generated by Django 3.1.7 on 2021-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_app', '0076_contactdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='voucher_prize',
            field=models.CharField(default='XXX', max_length=10),
            preserve_default=False,
        ),
    ]
